#include <QtWidgets/QApplication>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QPushbutton>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMessageBox>
#include <QtWidgets/QToolBar>  
#include <QtWidgets/QFileDialog>  
#include <QtGui/QStandardItemModel>
#include <QtGui/QScreen>
#include <QtGui/QPixmap>
#include <QtGui/QImageReader>
#include <QtGui/qevent.h>
#include <QtCore/QTimer>
#include <QtCore/QMimeData>
#include <QtCore/QFileInfo>
#include <QtCore/QProcess>
#include <QtCore/QDir>
